version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper-registry
    ports:
      - "2181:2181"
  jaeger:
    image: jaegertracing/all-in-one:1.36
    container_name: jaeger-tracing
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
